### ISSUE TITLE
Зачем делить на 1?

### ISSUE THREAD

**Issue by coursar** [alexsv95/02.CalcWallpaper#1]
https://github.com/alexsv95/02.CalcWallpaper/blob/27c1db8e091a05db6b134c06609d4313d2ffde41/src/ru/itpark/CalcWallPaper.java#L5

**Comment by alexsv95** [comment]
Fixed

1.06 - это ширина обойного рулона
Делим периметр комнаты на 1,06 – и получим значение N. Округляем результат в большую сторону – и получаем N полотнищ.

https://github.com/alexsv95/02.CalcWallpaper/blob/4961249b01f3f1a0ae1bb46895957de5b18231f0/src/ru/itpark/CalcWallPaper.java#L8-L9
