### ISSUE TITLE
Имена типа longWall2 - плохая идея

### ISSUE THREAD

**Issue by coursar** [alexsv95/02.CalcWallpaper#2]
https://github.com/alexsv95/02.CalcWallpaper/blob/27c1db8e091a05db6b134c06609d4313d2ffde41/src/ru/itpark/CalcWallPaper.java#L4

**Comment by alexsv95** [comment]
Исправлено

https://github.com/alexsv95/02.CalcWallpaper/blob/4961249b01f3f1a0ae1bb46895957de5b18231f0/src/ru/itpark/CalcWallPaper.java#L4
