### ISSUE TITLE
10 и 0.10 вынести в переменные, дать значащие имена

### ISSUE THREAD

**Issue by coursar** [alexsv95/02.CalcWallpaper#3]
https://github.com/alexsv95/02.CalcWallpaper/blob/27c1db8e091a05db6b134c06609d4313d2ffde41/src/ru/itpark/CalcWallPaper.java#L6

**Comment by alexsv95** [comment]
Fixed

https://github.com/alexsv95/02.CalcWallpaper/blob/4961249b01f3f1a0ae1bb46895957de5b18231f0/src/ru/itpark/CalcWallPaper.java#L6-L7

#3 исправлено в 4961249b01f3f1a0ae1bb46895957de5b18231f0
